### PR TITLE
Enable travis for Mac & Ubuntu 14.04 & 16.04 with 3 gcc versions

### PR DESCRIPTION
**Pull request by truth-quark**
This is an initial travis config for the testing repo. I'll remove the Not Ready for Merge once the tests pass.

### CODE REVIEW

**Comment by dstebila** [comment]
Could we break it up into different targets that cover different things?  We could have one set of targets that cover oqs_openssh, and additional sets of targets for each of the 4 oqs_openssl combinations {liboqs master, liboqs nist} x {1.0.2, 1.1.1}.  Would have to do some rearchitecting in the oqs_openssl integration test to support selecting a particular combination to test.

**Comment by truth-quark** [comment]
> Could we break it up into different targets that cover different things?

Does this idea relate to the custom branch option? (https://github.com/open-quantum-safe/testing/issues/11)

If the integration scripts were split into segments, we could tweak how these are called in the travis config. Did you have anything in particular in mind for splitting the tests up for travis?

**Comment by dstebila** [comment]
I updated the OpenSSL script to allow specifying particular repos/branches; see #14.

**Comment by truth-quark** [comment]
The pull request build failed as it went over the max time, so CI runs can be stopped due to factors outside our control. Consider splitting the run.sh calls into separate containers? (see #16)

**Pull request closed without merging**
