### PR TITLE
Add PQ auth to OpenSSH integration testing

### PR DESCRIPTION
**Pull request by dstebila**
Needed to code review open-quantum-safe/openssh-portable#22.

### CODE REVIEW

**Comment by dstebila** [comment]
@christianpaquin I've made some progress on the integration tests for OpenSSL PQ authentication, but ran into some failures that I haven't had a chance to diagnose yet.  (Some combinations pass, some fail.  Almost certainly it's just the script, not the OpenSSH code.)  I won't get to it today but can try later in the week unless you have a chance before then.

**Comment by christianpaquin** [comment]
I'll take a look

**Comment by dstebila** [comment]
@christianpaquin Working on some changes to this today, will let you know more soon.

**Comment by christianpaquin** [comment]
Sounds good; @dstebila. Just got hybrid auth working for OpenSSH, so I'll be ready to take over this if you need me to.

**Comment by dstebila** [comment]
Obsoleted by #28

**Pull request closed without merging**
